applications:
  - name: my-sample-app
    project: test
    source:
      repoURL: https://github.com/argoproj/argocd-example-apps.git
      targetRevision: HEAD
      path: guestbook
    destination:
      server: 'https://kubernetes.default.svc'
      namespace: default
    syncPolicy:
      automated: { }

projects:
  - name: test
    description: this is a test
    sourceRepos:
      - '*'
    destinations:
      - namespace: '*'
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    orphanedResources:
      warn: false
    additionalLabels: { }
    additionalAnnotations: { }