applications:
  - name: calculation
    project: calcproj
    source:
      repoURL: 'https://github.com/GustavoGuima86/calculationAPI'
      path: calculation
      targetRevision: HEAD
    destination:
      server: 'https://kubernetes.default.svc'
      namespace: test
    syncPolicy:
      automated: { }
  - name: calculation1
    project: default
    source:
      repoURL: 'https://github.com/GustavoGuima86/calculationAPI'
      path: calculation
      targetRevision: HEAD
    destination:
      server: 'https://kubernetes.default.svc'
      namespace: test
    syncPolicy:
      automated: { }
projects:
  - name: calcproj
    description: this is a test
    sourceRepos:
      - '*'
    destinations:
      - namespace: '*'
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: '*'
        kind: '*'
    orphanedResources:
      warn: false
    additionalLabels: { }
    additionalAnnotations: { }